# { "Depends": "py-genlayer:5jycge4q8k23462jtb0b9fyey1s9qz928sz2nbrd9mg4sxqg2qng" }
"""
Non -- a bonded constitutional tribunal on GenLayer.

Non settles one contested question on-chain:

    Does this proposal's material claims meet a pinned constitution under
    independently fetched evidence?

Outcomes: APPROVE | REJECT | REVISE | INCONCLUSIVE.

GenLayer owns the contested part: whether the proposal complies with the
case-pinned constitution version, and whether its material claims survive
evidence that each validator fetches for itself over HTTPS. The leader
does not get to assert a verdict and have it believed -- every validator
re-fetches the evidence, re-runs the prompt, and canonicalizes its own
verdict through the same pure code in contracts/non_lib.py. The leader's
result is accepted only when the two independently derived verdicts agree
on decision, outcome, and the case's pinned rules version.

Money makes a false verdict expensive. The proposer bonds GEN to open a
case; a challenger may bond during the appeal window. A final adverse
outcome forfeits the losing side's bond. INCONCLUSIVE refunds every bond
exactly -- there is no fee, and no silent approval, when the tribunal
cannot tell.

Studio Dev / Studio Next only (chain id 61997). State may reset.

This single file is what the network actually receives -- sibling imports
are not supported by contract validation, so scripts/build_bundle.py
inlines contracts/non_lib.py between the marker lines below. Do not
hand-edit the generated bundle; edit contracts/non_lib.py or this file and
re-run the bundler.
"""

import json
from datetime import datetime, timezone

import genlayer as gl
from genlayer.types import *
from genlayer.storage import TreeMap

# ===========================================================================
# BEGIN NON_LIB INLINE (generated by scripts/build_bundle.py -- do not
# hand-edit this block; edit contracts/non_lib.py and re-run the bundler)
# ===========================================================================
# ===========================================================================
# END NON_LIB INLINE
# ===========================================================================


# ---------------------------------------------------------------------------
# Deterministic transaction-time clock.
#
# datetime.now() is deterministic inside a GenLayer transaction (confirmed
# against genvm-linter's own safety exclusion list, which forbids
# time.time()/uuid.uuid4() but not datetime.now()). gl.vm.get_timestamp()
# is deliberately NOT used: it returns None under gltest direct-mode, which
# would make every window comparison untestable locally.
# ---------------------------------------------------------------------------


def _now_ts() -> int:
    return int(datetime.now(timezone.utc).timestamp())


def _sender() -> str:
    return str(gl.message.sender_address)


def _floor_config(raw, default: int) -> int:
    """Configurable minimums are floored at the protocol default: an
    operator may make Non stricter, never cheaper to lie to."""
    if raw is None or raw == "":
        return default
    try:
        value = int(str(raw))
    except (TypeError, ValueError):
        return default
    if value < default:
        return default
    return value


# ---------------------------------------------------------------------------
# Events (indexed logs -- not consensus state)
# ---------------------------------------------------------------------------


# An event's positional parameters are its INDEXED fields, and the SDK binds
# them by zipping the alphabetically SORTED field names against the values in
# positional order. If a declaration's parameter order is not already
# alphabetical, every value lands under the wrong name -- silently, since the
# emit still succeeds. So each declaration below is kept in alphabetical
# order, and tests/unit/test_events.py enforces that for all of them.
#
# The topic budget is ABI.EVENT_MAX_TOPICS == 4 INCLUDING the signature topic,
# so at most THREE indexed fields. A fourth makes emit fail on chain with
# `SystemError: 2: inval` (locally it is only a warning). Anything beyond
# three goes in the keyword blob instead.


class ScopeRegistered(gl.chain.Event):
    def __init__(self, admin: Address, scope_id: str, /): ...


class ConstitutionSet(gl.chain.Event):
    def __init__(self, scope_id: str, version: str, /): ...


class CaseOpened(gl.chain.Event):
    def __init__(self, case_id: str, proposer: Address, scope_id: str, /,
                 **blob): ...


class CaseDecided(gl.chain.Event):
    def __init__(self, case_id: str, decision: str, outcome: str, /): ...


class CaseChallenged(gl.chain.Event):
    def __init__(self, case_id: str, challenger: Address, /): ...


class CaseFinalized(gl.chain.Event):
    def __init__(self, case_id: str, decision: str, /): ...


class Claimed(gl.chain.Event):
    def __init__(self, amount: u256, claimant: Address, /): ...


# ---------------------------------------------------------------------------
# Contract
# ---------------------------------------------------------------------------


class Non(gl.contract.Contract):
    scopes: TreeMap[str, str]       # scope_id -> json {admin, constitution}
    cases: TreeMap[str, str]        # case_id  -> json case record
    claimable: TreeMap[str, u256]   # address  -> owed balance
    address_cases: TreeMap[str, str]  # address -> json list[case_id]
    scope_cases: TreeMap[str, str]  # scope_id -> json list[case_id]
    case_counter: u256
    treasury: str
    owner: str
    min_review_bond: u256
    min_challenge_bond: u256
    min_settle_bond: u256
    appeal_window: u256
    protocol_fee_bps: u256

    def __init__(self, treasury: str, appeal_window_seconds: str = "",
                 min_review_bond: str = "", min_challenge_bond: str = "",
                 min_settle_bond: str = ""):
        """Numeric constructor args cross the ABI as decimal strings --
        GenLayer calldata has no float type, and large wei values are not
        safely representable as JSON numbers. An empty string means "use
        the protocol default".

        Configurable values are floored at the protocol defaults: an
        operator may make Non stricter, never cheaper to lie to. The fee
        rate is fixed at deploy-time and is not operator-settable at all.
        """
        self.owner = Address(_sender()).as_hex
        self.treasury = Address(treasury).as_hex
        self.min_review_bond = u256(_floor_config(min_review_bond, MIN_REVIEW_BOND))
        self.min_challenge_bond = u256(_floor_config(min_challenge_bond, MIN_CHALLENGE_BOND))
        self.min_settle_bond = u256(_floor_config(min_settle_bond, MIN_SETTLE_BOND))
        self.appeal_window = u256(_floor_config(appeal_window_seconds, APPEAL_WINDOW_SECONDS))
        self.protocol_fee_bps = u256(PROTOCOL_FEE_BPS)

    # -----------------------------------------------------------------
    # internal helpers
    # -----------------------------------------------------------------

    def _load_scope(self, scope_id: str) -> dict:
        raw = self.scopes.get(scope_id)
        if raw is None:
            raise gl.vm.UserError(USER_ERRORS["SCOPE_MISSING"])
        return json.loads(raw)

    def _save_scope(self, scope_id: str, rec: dict) -> None:
        self.scopes[scope_id] = json.dumps(rec)

    def _load_case(self, case_id: str) -> dict:
        raw = self.cases.get(case_id)
        if raw is None:
            raise gl.vm.UserError(USER_ERRORS["CASE_MISSING"])
        return json.loads(raw)

    def _save_case(self, case_id: str, rec: dict) -> None:
        self.cases[case_id] = json.dumps(rec)

    def _credit(self, addr: str, amount: int) -> None:
        if not addr or amount <= 0:
            return
        current = int(self.claimable.get(addr, u256(0)))
        self.claimable[addr] = u256(current + amount)

    def _index(self, store: TreeMap[str, str], key: str, case_id: str) -> None:
        raw = store.get(key)
        ids = json.loads(raw) if raw else []
        if case_id not in ids:
            ids.append(case_id)
        store[key] = json.dumps(ids)

    # -----------------------------------------------------------------
    # scopes + constitutions
    # -----------------------------------------------------------------

    @gl.public.write
    def register_scope(self, scope_id: str, admin: str) -> str:
        """Claims a scope id and names its admin. Scope ids are first-come;
        a registered scope can never be re-registered by anyone else."""
        try:
            sid = validate_identifier(scope_id)
            admin_hex = Address(admin).as_hex
        except NonValidationError as exc:
            raise gl.vm.UserError(exc.code)
        except Exception:
            raise gl.vm.UserError(USER_ERRORS["BAD_SCOPE_ID"])

        if self.scopes.get(sid) is not None:
            raise gl.vm.UserError(USER_ERRORS["SCOPE_EXISTS"])

        self._save_scope(sid, {
            "scope_id": sid,
            "admin": admin_hex,
            "constitution": None,
            "created_at": _now_ts(),
        })
        ScopeRegistered(Address(admin_hex), sid).emit()
        return sid

    @gl.public.write
    def set_constitution(self, scope_id: str, version: str, rules_text: str,
                         rules_json: str) -> str:
        """Pins a new constitution version for a scope. Only the scope
        admin (or the contract owner, for bootstrap) may call this.

        Amendments are forward-only: every already-open case keeps the
        version it was opened under, so nobody can retroactively change the
        rules a live case is judged by.
        """
        sid = validate_identifier(scope_id) if isinstance(scope_id, str) else ""
        rec = self._load_scope(sid)
        sender = Address(_sender()).as_hex
        if sender != rec["admin"] and sender != self.owner:
            raise gl.vm.UserError(USER_ERRORS["NOT_SCOPE_ADMIN"])

        try:
            constitution = validate_constitution(version, rules_text, rules_json)
        except NonValidationError as exc:
            raise gl.vm.UserError(exc.code)

        constitution["set_at"] = _now_ts()
        rec["constitution"] = constitution
        self._save_scope(sid, rec)
        ConstitutionSet(sid, constitution["version"]).emit()
        return constitution["version"]

    # -----------------------------------------------------------------
    # open_case
    # -----------------------------------------------------------------

    @gl.public.write.payable
    def open_case(self, scope_id: str, subject_json: str, evidence_urls: str) -> str:
        """Opens a case against a scope's current constitution, freezing
        that version onto the case. Attached GEN is the review bond and
        must be at least min_review_bond.

        `evidence_urls` is a JSON array of HTTPS urls -- at least one, at
        most MAX_EVIDENCE_URLS, no private or loopback hosts.
        """
        sid = validate_identifier(scope_id) if isinstance(scope_id, str) else ""
        scope = self._load_scope(sid)
        constitution = scope.get("constitution")
        if not constitution:
            raise gl.vm.UserError(USER_ERRORS["CONSTITUTION_MISSING"])

        try:
            subject = validate_subject(subject_json)
            urls = validate_evidence_urls(evidence_urls)
            bond = validate_bond(gl.message.value, int(self.min_review_bond))
        except NonValidationError as exc:
            raise gl.vm.UserError(exc.code)

        counter = int(self.case_counter) + 1
        self.case_counter = u256(counter)
        case_id = make_case_id(counter)
        proposer = Address(_sender()).as_hex
        now_ts = _now_ts()

        rec = {
            "case_id": case_id,
            "scope_id": sid,
            "proposer": proposer,
            "subject": subject,
            "evidence_urls": urls,
            "rules_version": constitution["version"],
            "rules_text": constitution["rules_text"],
            "rules_json": constitution["rules_json"],
            "state": STATE_OPEN,
            "opened_at": now_ts,
            "decided_at": 0,
            "finalized_at": 0,
            "review_bond": str(bond),
            "challenger": "",
            "challenge_bond": "0",
            "challenge_note": "",
            "settler": "",
            "settle_bond": "0",
            "decision": "",
            "outcome": "",
            "scores": {},
            "reasoning": "",
            "weak_spots": "",
            "corrections": "",
            "improvements": "",
            "uncertainty": "",
            "evidence_report": [],
            "eval_rounds": 0,
            "settled": False,
        }
        self._save_case(case_id, rec)
        self._index(self.address_cases, proposer, case_id)
        self._index(self.scope_cases, sid, case_id)
        CaseOpened(case_id, Address(proposer), sid,
                   rules_version=constitution["version"]).emit()
        return case_id

    # -----------------------------------------------------------------
    # evaluate_case -- the single non-deterministic step
    # -----------------------------------------------------------------

    @gl.public.write
    def evaluate_case(self, case_id: str) -> str:
        """Runs the adjudication under the equivalence principle and writes
        the decision. Permissionless -- anyone may pay the gas to move a
        case forward; nobody can influence the result by doing so.

        Callable from OPEN (first evaluation) and from a challenged
        DECIDED case (re-evaluation with the challenger's added evidence).
        """
        rec = self._load_case(case_id)
        state = rec["state"]
        now_ts = _now_ts()

        if state == STATE_FINAL:
            raise gl.vm.UserError(USER_ERRORS["ALREADY_FINAL"])
        if state == STATE_DECIDED and not rec["challenger"]:
            raise gl.vm.UserError(USER_ERRORS["ALREADY_DECIDED"])
        if state == STATE_DECIDED and rec.get("eval_rounds", 0) >= 2:
            raise gl.vm.UserError(USER_ERRORS["ALREADY_DECIDED"])
        if state not in (STATE_OPEN, STATE_DECIDED):
            raise gl.vm.UserError(USER_ERRORS["NOT_OPEN"])

        rec["state"] = STATE_REVIEWING
        self._save_case(case_id, rec)

        # Plain local copies -- the ONLY values the nondet closures see.
        # Storage objects never cross into a nondeterministic block.
        urls = list(rec["evidence_urls"])
        subject = dict(rec["subject"])
        rules_version = rec["rules_version"]
        rules_text = rec["rules_text"]
        rules_json = rec["rules_json"]
        challenge_note = rec.get("challenge_note", "")

        def leader_fn() -> str:
            """Fetches every evidence url over HTTPS, normalizes each page
            into a record that carries its own limitations, and asks for a
            verdict. Runs identically on the leader and on every
            validator -- a validator never reads the leader's fetches."""
            records = []
            for url in urls:
                try:
                    page = gl.nondet.web.get(url)
                    body = getattr(page, "body", None)
                    if body is None:
                        body = str(page)
                    status = getattr(page, "status", 200)
                except Exception:
                    body = ""
                    status = 0
                records.append(normalize_evidence(url, status, body))

            evidence_ok = evidence_is_sufficient(records)
            if not evidence_ok:
                # Nothing was retrievable. Do not spend a prompt call to
                # reach a conclusion no evidence can support.
                verdict = canonicalize_verdict(
                    {"decision": DECISION_INCONCLUSIVE,
                     "outcome": "inconclusive",
                     "reasoning": "no evidence url could be retrieved"},
                    evidence_ok=False,
                )
            else:
                prompt = build_prompt(
                    rules_version=rules_version,
                    rules_text=rules_text,
                    rules_json=rules_json,
                    subject=subject,
                    evidence=records,
                    challenge_note=challenge_note,
                )
                try:
                    raw = gl.nondet.exec_prompt(prompt)
                except Exception:
                    raw = ""
                verdict = canonicalize_verdict(raw, evidence_ok=evidence_ok)

            verdict["rules_version"] = rules_version
            verdict["evidence"] = [{
                "url": r["url"],
                "status": r["status"],
                "ok": r["ok"],
                "title": r["title"],
                "limitations": r["limitations"],
            } for r in records]
            return json.dumps(verdict, sort_keys=True)

        def validator_fn(leader_result) -> bool:
            # The validator re-does the WHOLE job -- its own HTTPS fetches,
            # its own prompt, its own canonicalization -- and then compares
            # two independently derived verdicts. A leader that fabricated
            # a self-consistent envelope would pass a structural check; it
            # cannot pass this one unless the validator's own independent
            # work agrees on decision, outcome, and pinned rules version.
            # run_nondet hands the validator a `gl.vm.Return | gl.vm.VMError`,
            # NOT the leader's raw value -- the payload lives in .calldata.
            # str()-ing the wrapper yields a dataclass repr that never
            # parses as JSON, which would fail EVERY case closed.
            payload = getattr(leader_result, "calldata", None)
            if payload is None:
                return False  # VMError, or any shape without a return value
            try:
                leader_verdict = json.loads(str(payload))
            except (json.JSONDecodeError, TypeError):
                return False
            if not isinstance(leader_verdict, dict):
                return False

            mine = json.loads(leader_fn())
            return verdicts_equivalent(
                leader_verdict,
                mine,
                rules_version_match=(
                    leader_verdict.get("rules_version") == mine.get("rules_version")
                ),
            )

        raw_result = gl.vm.run_nondet(leader_fn, validator_fn)

        try:
            agreed = json.loads(str(raw_result))
        except (json.JSONDecodeError, TypeError):
            agreed = {}
        if not isinstance(agreed, dict):
            agreed = {}

        # Re-canonicalize the agreed result inside deterministic code. Even
        # a consensus-accepted envelope is re-run through the same pure
        # mapping before it is allowed to touch stored state.
        evidence_records = agreed.get("evidence", [])
        evidence_ok = any(bool(e.get("ok")) for e in evidence_records) \
            if isinstance(evidence_records, list) else False
        verdict = canonicalize_verdict(agreed, evidence_ok=evidence_ok)

        if agreed.get("rules_version") and agreed["rules_version"] != rules_version:
            # A verdict reached under a different rules version is not a
            # verdict about this case.
            verdict = canonicalize_verdict({}, evidence_ok=False)

        rec = self._load_case(case_id)
        rec["decision"] = verdict["decision"]
        rec["outcome"] = verdict["outcome"]
        rec["scores"] = {
            "score": verdict["score"],
            "fit_score": verdict["fit_score"],
            "risk": verdict["risk"],
        }
        rec["reasoning"] = verdict["reasoning"]
        rec["weak_spots"] = verdict["weak_spots"]
        rec["corrections"] = verdict["corrections"]
        rec["improvements"] = verdict["improvements"]
        rec["uncertainty"] = verdict["uncertainty"]
        rec["evidence_report"] = evidence_records if isinstance(evidence_records, list) else []
        rec["state"] = STATE_DECIDED
        rec["decided_at"] = now_ts
        rec["eval_rounds"] = int(rec.get("eval_rounds", 0)) + 1
        self._save_case(case_id, rec)

        CaseDecided(case_id, verdict["decision"], verdict["outcome"]).emit()
        return verdict["decision"]

    # -----------------------------------------------------------------
    # challenge
    # -----------------------------------------------------------------

    @gl.public.write.payable
    def challenge(self, case_id: str, note: str, extra_urls: str = "") -> str:
        """Bonds against a decided case during its appeal window. A
        challenger may add evidence, never remove it, and may not be the
        proposer -- self-challenging would let one party manufacture a
        two-sided case and collect from itself.

        A challenge reopens the case for exactly one re-evaluation.
        """
        rec = self._load_case(case_id)
        now_ts = _now_ts()

        if rec["state"] != STATE_DECIDED:
            raise gl.vm.UserError(USER_ERRORS["NOT_DECIDED"])
        if not appeal_is_open(rec["decided_at"], now_ts, int(self.appeal_window)):
            raise gl.vm.UserError(USER_ERRORS["APPEAL_CLOSED"])
        if rec["challenger"]:
            raise gl.vm.UserError(USER_ERRORS["ALREADY_CHALLENGED"])

        challenger = Address(_sender()).as_hex
        if challenger == rec["proposer"]:
            raise gl.vm.UserError(USER_ERRORS["SELF_CHALLENGE"])

        try:
            bond = validate_bond(gl.message.value, int(self.min_challenge_bond))
            extra = validate_evidence_urls(extra_urls, allow_empty=True) \
                if extra_urls else []
        except NonValidationError as exc:
            raise gl.vm.UserError(exc.code)

        rec["challenger"] = challenger
        rec["challenge_bond"] = str(bond)
        rec["challenge_note"] = clamp_text(note, MAX_NOTE_CHARS)
        rec["evidence_urls"] = merge_evidence_urls(rec["evidence_urls"], extra)
        rec["challenged_at"] = now_ts
        self._save_case(case_id, rec)
        self._index(self.address_cases, challenger, case_id)

        CaseChallenged(case_id, Address(challenger)).emit()
        return case_id

    # -----------------------------------------------------------------
    # finalize
    # -----------------------------------------------------------------

    @gl.public.write.payable
    def finalize(self, case_id: str) -> str:
        """Closes a case and writes the bond ledger.

        Permissionless after the appeal window. Attached GEN is an optional
        liveness deposit: it is always returned to whoever posted it, and
        any amount below min_settle_bond is simply treated as zero rather
        than reverting -- finalization must never be blocked by a fee.

        A challenged case must be re-evaluated (eval_rounds >= 2) before it
        can be finalized, so a challenge always actually buys a second look.
        """
        rec = self._load_case(case_id)
        now_ts = _now_ts()

        if rec["state"] == STATE_FINAL:
            raise gl.vm.UserError(USER_ERRORS["ALREADY_FINAL"])
        if rec["state"] != STATE_DECIDED:
            raise gl.vm.UserError(USER_ERRORS["NOT_DECIDED"])
        if appeal_is_open(rec["decided_at"], now_ts, int(self.appeal_window)):
            raise gl.vm.UserError(USER_ERRORS["APPEAL_OPEN"])
        if rec["challenger"] and int(rec.get("eval_rounds", 0)) < 2:
            raise gl.vm.UserError(USER_ERRORS["NOT_DECIDED"])

        settler = Address(_sender()).as_hex
        attached = int(gl.message.value)
        settle_bond = attached if attached >= int(self.min_settle_bond) else 0
        if attached > 0 and settle_bond == 0:
            # Too small to count as a liveness deposit, but it is still the
            # caller's money. Credit it straight back.
            self._credit(settler, attached)

        accounting = settle_accounting(
            decision=rec["decision"],
            proposer=rec["proposer"],
            review_bond=int(rec["review_bond"]),
            challenger=rec["challenger"],
            challenge_bond=int(rec["challenge_bond"]),
            settler=settler,
            settle_bond=settle_bond,
            treasury=self.treasury,
        )
        for addr, amount in accounting["credits"].items():
            self._credit(addr, amount)

        rec["state"] = STATE_FINAL
        rec["finalized_at"] = now_ts
        rec["settler"] = settler
        rec["settle_bond"] = str(settle_bond)
        rec["settled"] = True
        self._save_case(case_id, rec)

        CaseFinalized(case_id, rec["decision"]).emit()
        return rec["decision"]

    # -----------------------------------------------------------------
    # claim
    # -----------------------------------------------------------------

    @gl.public.write
    def claim(self) -> u256:
        """The only method that moves GEN out of the contract. Pays the
        caller their whole ledger balance across every case they have
        touched, so the last claimant of a multi-party pot is never left
        holding dust."""
        sender = Address(_sender()).as_hex
        owed = int(self.claimable.get(sender, u256(0)))
        if owed <= 0:
            raise gl.vm.UserError(USER_ERRORS["NOTHING_TO_CLAIM"])

        self.claimable[sender] = u256(0)
        gl.contract.get_at(gl.message.sender_address).emit_transfer(value=u256(owed))
        Claimed(u256(owed), gl.message.sender_address).emit()
        return u256(owed)

    # -----------------------------------------------------------------
    # views
    # -----------------------------------------------------------------

    @gl.public.view
    def get_config(self) -> str:
        return json.dumps({
            "treasury": self.treasury,
            "owner": self.owner,
            "min_review_bond": str(int(self.min_review_bond)),
            "min_challenge_bond": str(int(self.min_challenge_bond)),
            "min_settle_bond": str(int(self.min_settle_bond)),
            "appeal_window_seconds": int(self.appeal_window),
            "protocol_fee_bps": int(self.protocol_fee_bps),
            "max_evidence_urls": MAX_EVIDENCE_URLS,
            "score_tolerance": SCORE_TOLERANCE,
            "decisions": list(DECISIONS),
            "case_count": int(self.case_counter),
        })

    @gl.public.view
    def get_constitution(self, scope_id: str) -> str:
        rec = self._load_scope(scope_id.strip().lower())
        return json.dumps({
            "scope_id": rec["scope_id"],
            "admin": rec["admin"],
            "constitution": rec.get("constitution"),
        })

    @gl.public.view
    def get_case(self, case_id: str) -> str:
        rec = self._load_case(case_id)
        rec["derived_state"] = case_state(rec, _now_ts(), int(self.appeal_window))
        rec["appeal_deadline"] = appeal_deadline(
            rec["decided_at"], int(self.appeal_window)
        ) if rec["decided_at"] else 0
        return json.dumps(rec)

    @gl.public.view
    def get_case_evidence(self, case_id: str) -> str:
        rec = self._load_case(case_id)
        return json.dumps({
            "case_id": case_id,
            "urls": rec["evidence_urls"],
            "report": rec.get("evidence_report", []),
        })

    @gl.public.view
    def get_claimable(self, address: str) -> str:
        key = Address(address).as_hex
        return str(int(self.claimable.get(key, u256(0))))

    @gl.public.view
    def list_cases(self, scope_id: str = "") -> str:
        """Case ids only -- the on-chain truth for any single case is
        get_case. A UI reads this index and then fetches each ticket."""
        if scope_id:
            raw = self.scope_cases.get(scope_id.strip().lower())
        else:
            raw = None
        if raw is not None:
            return raw
        if scope_id:
            return "[]"
        count = int(self.case_counter)
        return json.dumps([make_case_id(i) for i in range(1, count + 1)])

    @gl.public.view
    def list_cases_for(self, address: str) -> str:
        key = Address(address).as_hex
        raw = self.address_cases.get(key)
        return raw if raw is not None else "[]"
